version: "3.7"
services:
  app:
    build:
      args:
        user: pe
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: giftcards
    container_name: giftcards-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - giftcards

  db:
    image: mysql:5.7
    container_name: giftcards-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - giftcards

  nginx:
    image: nginx:alpine
    container_name: giftcards-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - giftcards

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
    networks:
      - giftcards

networks:
  giftcards:
    driver: bridge
